use programmers_db;

-- 코드를 입력하세요
SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK_SALES.SALES * BOOK.PRICE) AS TOTAL_SALES
FROM BOOK JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID JOIN 
      (SELECT *
      FROM BOOK_SALES
      WHERE SALES_DATE LIKE '2022-01-%'
      ) BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
GROUP BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY DESC