use programmers_db;

-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM (SELECT *
      FROM APPOINTMENT
      WHERE DATE(APNT_YMD) = '2022-04-13' AND APNT_CNCL_YN = 'N' AND MCDP_CD = 'CS') A 
      JOIN PATIENT P ON A.PT_NO = P.PT_NO JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
ORDER BY A.APNT_YMD