use programmers_db;

-- 코드를 작성해주세요
SELECT 
	B.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM 
	BOOK AS B JOIN BOOK_SALES AS BS ON B.BOOK_ID = BS.BOOK_ID
WHERE 
	SALES_DATE LIKE ("2022-01-%")
GROUP BY 
	CATEGORY
ORDER BY 
	CATEGORY