USE programmers_db;

CREATE TABLE FIRST_HALF 
(
	SHIPMENT_ID INTEGER NOT NULL,
    FLAVOR VARCHAR(20) NOT NULL,
    SHIPMENT_ID INTEGER NOT NULL
);

INSERT INTO FIRST_HALF VALUES(104,	'caramel',	26000);
INSERT INTO FIRST_HALF VALUES(101,	'chocolate',	3200);
INSERT INTO FIRST_HALF VALUES(103,	'mint_chocolate',	1700);
INSERT INTO FIRST_HALF VALUES(106,	'peach',	2450);
INSERT INTO FIRST_HALF VALUES(109,	'strawberry',	3100);
INSERT INTO FIRST_HALF VALUES(102,	'vanilla',	2800);
INSERT INTO FIRST_HALF VALUES(105,	'white_chocolate',	3100);