USE programmers_db;

CREATE TABLE JULY
(
	SHIPMENT_ID INTEGER NOT NULL,
    FLAVOR VARCHAR(20) NOT NULL,
    SHIPMENT_ID INTEGER NOT NULL
);

INSERT INTO JULY VALUES(101,	'chocolate',	520);
INSERT INTO JULY VALUES(102,	'vanilla',	560);
INSERT INTO JULY VALUES(103,	'mint_chocolate',	400);
INSERT INTO JULY VALUES(104,	'caramel',	460);
INSERT INTO JULY VALUES(105,	'white_chocolate',	350);
INSERT INTO JULY VALUES(106,	'peach',	500);
INSERT INTO JULY VALUES(109,	'strawberry',	520);
INSERT INTO JULY VALUES(209,	'strawberry',	220);